### ISSUE TITLE
Consider an ordered list 

### ISSUE THREAD

**Issue by nipunbatra** [neeldhara/ClassPlan#1]
One immediate benefit of using an ordered list is to see the number of classes I'd have in total. 

perhaps the only change needed is to change the `<ul>` and `<\ul>` to `<ol>`
https://github.com/neeldhara/ClassPlan/blob/d82ccab9c3d71363fc75b6fa6eed99403952d8c5/index.html#L36

**Comment by neeldhara** [comment]
Good point! Updated. Thanks for the suggestion 🙌
